# Proyecto RL DEFI IV

**Integrantes**: Juan Camilo y Jesús Figueroa

**Descripción**:

Creación de un agente de aprendizaje por refuerzo para operar el token POL, empleando el histórico de transacciones on-chain y métricas financieras para identificar wallets con desempeño consistente, construir un perfil estadístico de su comportamiento e incorporar dicho perfil al proceso de toma de decisiones del agente, con el propósito de mejorar las decisiones de compra, venta o hold del activo.

El sistema reconstruirá el historial de actividad de las wallets seleccionadas, se usaran el precio de cierre de POL-USD en ventanas de 1m, 5m, 15m y 1h, con el objetivo de calcular la ganancia generada en esas ventanas.

## Imports

In [7]:
from utils.swap import SwapPipeline
from utils.wallet import WalletView

## Main Transacciones

In [8]:
API_KEY = 'alch_C0KE9IzZP8RqJnRzjbxML'
RPC_URL      = f"https://polygon-mainnet.g.alchemy.com/v2/{API_KEY}"
POOL_ADDRESS = "0xA374094527e1673A86dE625aa59517c5dE346d32"  # WPOL/USDC 0.05%

TICKER_YF    = "POL28321-USD"
DECIMALES_T0 = 18   # WPOL
DECIMALES_T1 = 6    # USDC
NOMBRE_T0    = "pol"
NOMBRE_T1    = "usdc"

HORAS        = 24
HORIZONTES   = ["1m", "5m", "15m", "1h"]
CACHE_PATH   = "cache/swaps_24h.parquet"

In [ ]:
pipeline = SwapPipeline(
    rpc_url      = RPC_URL,
    pool_address = POOL_ADDRESS,
    ticker_yf    = TICKER_YF,
    decimales_t0 = DECIMALES_T0,
    decimales_t1 = DECIMALES_T1,
    nombre_t0    = NOMBRE_T0,
    nombre_t1    = NOMBRE_T1,
    cache_path   = CACHE_PATH,
)

swaps = pipeline.ejecutar(
    horas            = HORAS,
    horizontes       = HORIZONTES,
    forzar_descarga  = False,
    verbose          = True,
)

In [10]:
# Tabla de Swaps
swaps.head()

,timestamp,bloque,hash_tx,wallet,direccion,pol_cantidad,usdc_cantidad,precio_ejecutado,gas_pol,gas_usdc,...,ganancia_usdc_1m,precio_fwd_5m,retorno_5m,ganancia_usdc_5m,precio_fwd_15m,retorno_15m,ganancia_usdc_15m,precio_fwd_1h,retorno_1h,ganancia_usdc_1h
0,2026-08-21 20:47:52-05:00,92438830,0xba45eff7940a3e13a3efe6650f54d9f9fd7995d84a24...,0x49fB304bA92f732486d23DE10d5824ff67A85F75,Sell,56.976172,5.453435,0.095714,0.240044,0.022976,...,-0.004882,0.09531,0.004224,0.023036,0.09616,-0.004656,-0.025394,0.09907,-0.035059,-0.191194
1,2026-08-21 20:48:36-05:00,92438859,0x8cc4fd5c05fd576cfd6d216e2231d7b89cfa8f915de9...,0xe27D4Cb1759BAE0188126bD62D415a6Fa528FFE5,Buy,210.691960,20.189782,0.095826,1.328537,0.127308,...,-0.051845,0.09531,-0.005385,-0.108731,0.09616,0.003485,0.070357,0.09907,0.033852,0.683470
2,2026-08-21 20:49:03-05:00,92438877,0x42520a2fd84fbe4ed8b9cc301cbb319a0497410ff00e...,0xeba3A54cffcC11123578C5A740a45456d5C6D4a8,Sell,222.132001,21.264494,0.095729,0.071096,0.006806,...,0.033118,0.09531,0.004378,0.093092,0.09616,-0.004501,-0.095720,0.09907,-0.034900,-0.742123
3,2026-08-21 20:49:12-05:00,92438883,0x02a30b4fb5bcc347379ffecbe0211c4ec566e2d9db77...,0xeba3A54cffcC11123578C5A740a45456d5C6D4a8,Sell,191.333283,18.307962,0.095686,0.070256,0.006722,...,0.020327,0.09531,0.003932,0.071986,0.09616,-0.004951,-0.090647,0.09907,-0.035363,-0.647426
4,2026-08-21 20:49:52-05:00,92438910,0x0087aed6f5d9d6a2d612db08ac0246dd39bb1eeff959...,0xeba3A54cffcC11123578C5A740a45456d5C6D4a8,Sell,224.353321,21.457538,0.095642,0.086444,0.008268,...,0.013848,0.09531,0.003468,0.074422,0.09616,-0.005419,-0.116278,0.09907,-0.035845,-0.769145

## Main Wallets

In [12]:
# Para Historial de Wallets
wallets = WalletView(pipeline, horizontes=HORIZONTES)

In [13]:
# Historial
wallets.construir()

,wallet,direccion,n_swaps,pol_cantidad,usdc_cantidad,gas_usdc,usdc_neto,ganancia_neta_usdc_1m,ganancia_neta_usdc_5m,ganancia_neta_usdc_15m,ganancia_neta_usdc_1h
0,0x003AB61c1f180Eee803b9EA334B6b1B29A4c8364,Sell,1,777.660000,84.096490,0.029387,84.067103,-0.122368,-0.977797,0.484208,0.095377
1,0x004125dc64f050C3CCEaD24A61c89aDDD4C2c794,Buy,1,111.208914,11.962802,0.047072,11.915730,-0.081605,-0.078270,-0.099399,-0.352956
2,0x0051391747B6C11110dA7dE76B3F4AED532d7E40,Buy,1,121.204415,12.272375,0.062058,12.210317,-0.117028,0.329004,0.579898,1.261067
3,0x007d9668D19418b66CD028cde1Ea598260152F93,Buy,1,13.590998,1.495507,0.042197,1.453310,-0.038889,-0.038753,-0.018910,-0.047587
4,0x0082CaF47363bD42917947d81f4d4E0395257267,Buy,1,137.456061,14.998583,0.181089,14.817494,-0.239573,-0.521357,-0.558471,0.238775
...,...,...,...,...,...,...,...,...,...,...,...
3053,0xfd50D4D48896e076A02Bd5F7534df1244948eAAE,Sell,1,282.750000,30.054951,0.012830,30.042121,0.064965,-0.260196,-0.279988,-0.427018
3054,0xfeA573eF9d5eD5b470311582C99c103C38C0320f,Buy,1,0.002269,0.000243,0.020015,0.000000,-0.020016,-0.020015,-0.020018,-0.020022
3055,0xff7D510CF1ec1d376DB53e45bC754bDd8c041D3e,Buy,1,8.954345,1.032616,0.113928,0.918688,-0.109094,-0.095483,-0.081783,-0.133181
3056,0xff91d71CdbA995Bb2F2Ad009F2309E542036Ebd2,Buy,1,15.822873,1.739953,0.043565,1.696388,-0.053604,-0.039363,-0.036515,-0.027496
3057,0xffDA25a07DE89c181A5A97F78590778A86FA2635,Sell,1,35.254056,3.691420,0.010037,3.681383,0.000860,0.048805,-0.138394,-0.269539